fix build

diff --git a/cdemo/build b/cdemo/build
--- a/cdemo/build
+++ b/cdemo/build
@@ -11,10 +11,12 @@ if [ $# -ne 0 ] ; then
 fi
 
 for PROG in "${PROGARR[@]}" ; do
-    gcc $PROG.c -o $PROG
-    if [ $? -ne 0 ] ; then
-	echo "build error: "$PROG
-	exit $?
+    if [ -e $PROG.c ] ; then
+	gcc $PROG.c -o $PROG
+	if [ $? -ne 0 ] ; then
+	    echo "build error: "$PROG
+	    exit $?
+	fi
     fi
 done
 echo "built all"
